{
 "title": "lotus",
 "tags": [
  "Filecoin",
  "多集群"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(lotus_current_time{}, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(lotus_current_time{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "miner_id",
    "label": "miner",
    "query": {
     "query": "label_values(lotus_miner_sector_size{instance=~\"$instance\"}, miner_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_current_time{job=\"$job\",instance=\"$instance\"} * 1000",
     "legendFormat": "当前时间"
    },
    {
     "expr": "lotus_scrape_duration{job=\"$job\",instance=\"$instance\",collector=\"all\"}",
     "legendFormat": "延迟"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_current_epoch{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "当前高度"
    },
    {
     "expr": "sum(lotus_sync{job=\"$job\",instance=\"$instance\"}) by (api,env,instance,job)",
     "legendFormat": "高度差"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "attoFIL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_base_fee{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "基础费率"
    }
   ]
  },
  {
   "title": "余额总览",
   "type": "bargauge",
   "description": "可用余额包含各节点Available、Worker、Owner账户总和；保留余额为各节点Control账户余额，主要用于提交窗口证明。",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Fil" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum ({__name__=\"lotus_actor_balance\",tag!~\"control.*|balance|pledge|pre_commit|vesting\",miner_id!~\"external.*\",job=\"$job\",instance=\"$instance\"}) by (api,env,instance,__name__,job)",
     "legendFormat": "可用余额"
    },
    {
     "expr": "sum ({__name__=\"lotus_actor_balance\",tag=~\"control.*\",miner_id!~\"external.*\",job=\"$job\",instance=\"$instance\"}) by (api,env,instance,__name__,job)",
     "legendFormat": "保留余额"
    }
   ]
  },
  {
   "title": "独立钱包",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Fil" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{__name__=\"lotus_actor_balance\",miner_id=~\".*external.*\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "节点余额",
   "type": "bargauge",
   "description": "不包含control账户",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Fil" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum ({__name__=\"lotus_actor_balance\",tag!~\"control.*|balance|pledge|pre_commit|vesting\",miner_id!~\"external.*\",job=\"$job\",instance=\"$instance\"}) by (miner_id,api,env,instance,__name__,job,miner_tag)",
     "legendFormat": "{{miner_id}} {{miner_tag}}"
    }
   ]
  },
  {
   "title": "当前窗口信息",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 3 },
   "targets": [
    { "expr": "lotus_miner_deadline_info{}" },
    {
     "expr": "{__name__=\"lotus_miner_deadline_open_time\",job=\"$job\",instance=\"$instance\"}* 1000 and ignoring(open_epoch,period_start) {__name__=\"lotus_miner_deadline_info\",job=\"$job\",instance=\"$instance\"} "
    },
    {
     "expr": "{__name__=\"lotus_miner_deadline_sector_all\",job=\"$job\",instance=\"$instance\"} and ignoring(open_epoch,period_start) {__name__=\"lotus_miner_deadline_info\",job=\"$job\",instance=\"$instance\"}"
    },
    {
     "expr": "{__name__=\"lotus_miner_deadline_sector_faulty\",job=\"$job\",instance=\"$instance\"} and ignoring(open_epoch,period_start) {__name__=\"lotus_miner_deadline_info\",job=\"$job\",instance=\"$instance\"}"
    },
    {
     "expr": "{__name__=\"lotus_miner_deadline_partitions\",job=\"$job\",instance=\"$instance\"} and ignoring(open_epoch,period_start) {__name__=\"lotus_miner_deadline_info\",job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "节点质押",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Fil" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum ({__name__=\"lotus_actor_balance\",tag=\"pledge\",miner_id!~\"external.*\",job=\"$job\",instance=\"$instance\"}) by (miner_id,api,env,instance,__name__,job,miner_tag)",
     "legendFormat": "{{miner_id}} {{miner_tag}}"
    }
   ]
  },
  {
   "title": "节点算力",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum ({__name__=\"lotus_miner_quality_adj_power\",job=\"$job\",instance=\"$instance\"}) by (miner_id,api,env,instance,__name__,job,miner_tag)",
     "legendFormat": "{{miner_id}} {{miner_tag}}"
    }
   ]
  },
  {
   "title": "错误扇区",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "lotus_miner_deadline_sector_faulty{job=\"$job\",instance=\"$instance\"} > 0"
    }
   ]
  },
  { "title": "余额详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "$miner_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "repeat": "miner_id",
   "fieldConfig": { "defaults": { "unit": "Fil" } },
   "targets": [
    {
     "expr": "{__name__=\"lotus_actor_balance\",job=\"$job\",instance=\"$instance\",miner_id=\"$miner_id\"}",
     "legendFormat": "{{tag}} - {{address}}"
    }
   ]
  },
  { "title": "Deadlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "$miner_id",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 40 },
   "repeat": "miner_id",
   "targets": [
    {
     "expr": "lotus_miner_deadline_open_epoch{job=\"$job\",instance=\"$instance\",miner_id=\"$miner_id\"}"
    },
    {
     "expr": "lotus_miner_deadline_open_time{job=\"$job\",instance=\"$instance\",miner_id=\"$miner_id\"} * 1000"
    },
    {
     "expr": "lotus_miner_deadline_partitions{job=\"$job\",instance=\"$instance\",miner_id=\"$miner_id\"}"
    },
    {
     "expr": "lotus_miner_deadline_partitions_proven{job=\"$job\",instance=\"$instance\",miner_id=\"$miner_id\"}"
    },
    {
     "expr": "lotus_miner_deadline_sector_all{job=\"$job\",instance=\"$instance\",miner_id=\"$miner_id\"}"
    },
    {
     "expr": "lotus_miner_deadline_sector_faulty{job=\"$job\",instance=\"$instance\",miner_id=\"$miner_id\"}"
    },
    {
     "expr": "lotus_miner_deadline_sector_recovery{job=\"$job\",instance=\"$instance\",miner_id=\"$miner_id\"}"
    }
   ]
  }
 ]
}